apiVersion: v1
kind: Service
metadata:
  name: controller-manager-service
  namespace: system
  annotations:
    # TODO[aleskandro]: what to do in non-openshift environments?
    service.beta.openshift.io/serving-cert-secret-name: webhook-server-cert
spec:
  ports:
    - port: 443
      targetPort: 9443
  selector:
    control-plane: controller-manager