kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
  - ../default

patches:
  - patch: |
      - op: add
        path: /metadata/annotations
        value:
          service.beta.openshift.io/inject-cabundle: "true"
    target:
      group: apiextensions.k8s.io
      version: v1
      kind: CustomResourceDefinition
      name: clusterpodplacementconfigs.multiarch.openshift.io
